### ISSUE TITLE
Removing links

### ISSUE THREAD

**Issue by BloggerStrange** [Pligg/pligg-cms#251] opened 2016-04-21 18:04 UTC
How to remove this link "What is Kliqqi?
Kliqqi is an open source content management system that lets you easily create your own user-powered website." from sidebar.
 and "made with kliqqi" from footer ???

**Comment by redwinefireplace** [comment] 2016-04-21 18:10
This is not the right place to post your question; it is only for bugs issues. Please use the Kliqqi forum

http://www.kliqqi.com/forum/

**Comment by chuckroastpligg** [comment] 2016-04-21 18:11
Closing this since it's not a bug.

**Closed as completed by chuckroastpligg** 2016-04-21 18:11 UTC
