### ISSUE TITLE
pligg adds extra characters to the submitted urls 

### ISSUE THREAD

**Issue by tamouchin** [Pligg/pligg-cms#206] opened 2015-01-31 18:13 UTC
When my site members submit a story 10 percent of them could not be opened because pligg changes the urls and adds some extra characters to the end of original url to make them not to get open. checking the subject showed that it is a real bug with pligg that they cannot find a way to solve it. If anybody has found a way for this please help me.

**Comment by chuckroastpligg** [comment] 2015-01-31 21:37
You'll need to be more descriptive. Pligg does not change the URLs unless you've made changes in the admin panel that you probably shouldn't have. Please provide examples of both the url being submitted and the url that it's being changed to.. I'm almost 99% sure this is an administration/configuration error and not a bug.

**Comment by tamouchin** [comment] 2015-02-01 00:11
Ok, let me give you example. this link is submitted on my website 
www.linkbezar.com
https://royayeazadi.wordpress
com/2015/01/31/%D8%AA%D8%A8%D8%B1%DB%8C%DA%A9-%D9%88-%D8%AF%D8%B1%D8%AF%D8%AF
D9%84-%D9%85%D8%A7%D8%AF%D8%B1-%D8%B1%DB%8C%D8%AD%D8%A7%D9%86%D9%87-%D8%A8%D9
87-%D8%A2%D8%AA%D9%86%D8%A7-%D9%81%D8%B1%D9%82%D8%AF%D8%A7/

Clicked on it and got error 404. Checked the link it was changed as below
https://royayeazadi.wordpress
com/2015/01/31/%D8%AA%D8%A8%D8%B1%DB%8C%DA%A9-%D9%88-%D8%AF%D8%B1%D8%AF%D8%AF
D9%84-%D9%85%D8%A7%D8%AF%D8%B1-%D8%B1%DB%8C%D8%AD%D8%A7%D9%86%D9%87-%D8%A8%D9
87-%D8%A2%D8%A

Putting the first URL in a browser opens the article which belongs to. But
the second one from my website does not do so. Because there has been a
change in that. Actually this time pligg has removed a part of UrL. That is
not always it removes most of the time it adds to it , and not for every URL
but about %10 of Them specially with Persian words in URL. And not for all
URLs with persian words but about % 5 o6 6 of them. This happens with Urls
in English too
I appreciate any possible help because this is a ,, put your link,, website
and has many members and thousands of users everyday. Now I am comming to
lose my members and users. 
Tamouchin

-------Original Message-------
 
From: chuckroastpligg
Date: 1/31/2015 9:37:40 PM
To: Pligg/pligg-cms
Cc: tamouchin
Subject: Re: [pligg-cms] pligg adds extra characters to the submitted urls
(#206)
 
You'll need to be more descriptive. Pligg does not change the URLs unless
you've made changes in the admin panel that you probably shouldn't have.
Please provide examples of both the url being submitted and the url that it
s being changed to.. I'm almost 99% sure this is an
administration/configuration error and not a bug. 
—
Reply to this email directly or view it on GitHub.
 

---
Denne e-posten har blitt sjekket for virus av antivirusprogramvare fra Avast
http://www.avast.com

**Comment by chuckroastpligg** [comment] 2015-02-01 00:21
That is Unicode.. Try turning off url validation in admin > submit > validate url > set to false. Then try submitting a new link and see if it still happens.. Make sure you are submitting a NEW URL after changing that setting. See if that makes a difference.

**Comment by tamouchin** [comment] 2015-02-01 00:30
I already have don it and put it in false and true several times from the
first day 3 moths ago when I started the job and got the problem. But no use
 It does the same.  

 
 
 
-------Original Message-------
 
From: chuckroastpligg
Date: 2/1/2015 12:21:55 AM
To: Pligg/pligg-cms
Cc: tamouchin
Subject: Re: [pligg-cms] pligg adds extra characters to the submitted urls
(#206)
 
That is Unicode.. Try turning off url validation in admin > submit >
validate url > set to false. Then try submitting a new link and see if it
still happens.. Make sure you are submitting a NEW URL after changing that
setting. See if that makes a difference. 
—
Reply to this email directly or view it on GitHub.
 

---
Denne e-posten har blitt sjekket for virus av antivirusprogramvare fra Avast
http://www.avast.com

**Comment by tamouchin** [comment] 2015-02-01 00:33
The strange thing is the same URLs work on my opponent website www.balatarin
com but not on mine.
 
 
 
 
 
-------Original Message-------
 
From: chuckroastpligg
Date: 2/1/2015 12:21:55 AM
To: Pligg/pligg-cms
Cc: tamouchin
Subject: Re: [pligg-cms] pligg adds extra characters to the submitted urls
(#206)
 
That is Unicode.. Try turning off url validation in admin > submit >
validate url > set to false. Then try submitting a new link and see if it
still happens.. Make sure you are submitting a NEW URL after changing that
setting. See if that makes a difference. 
—
Reply to this email directly or view it on GitHub.
 

---
Denne e-posten har blitt sjekket for virus av antivirusprogramvare fra Avast
http://www.avast.com

**Comment by tamouchin** [comment] 2015-02-01 11:47
After putting validation to false after our last talk I faced the first
change in URL now. This URL has been Changed
http://motorsportiran
ir/%D8%A7%D9%88%D9%84%D9%8A%D9%86-%D8%AA%D8%B5%D9%88%D9%8A%D8%B1-%D8%AC%D8%A7
D8%B3%D9%88%D8%B3%D9%8A-%D8%A7%D8%B2-%D9%84%D8%A7%D9%85%D8%A8%D9%88%D8%B1%DA%
F%D9%8A%D9%86%D9%8A-%D8%A7%D9%88%D9%86%D8%AA/


To this one and unable to get opened. 
 
http://motorsportiran
ir/%D8%A7%D9%88%D9%84%D9%8A%D9%86-%D8%AA%D8%B5%D9%88%D9%8A%D8%B1-%D8%AC%D8%A7
D8%B3%D9%88%D8%B3%D9%8A-%D8%A7%D8%B2-%D9%84%D8%A7%D9%85%D8%A8%D9%88%D8%B1%DA%
F%D9%8A%D9%86%D9%8A-%D

As you see it has removed this part of original URL.
8%A7%D9%88%D9%86%D8%AA/

What can we do with this, nobody has the answer. I will pay for anybody to
fix it but no one was able to do the job. I am about to move from pligg to
something like Reddit maybe it will help.
The only way I found to this is just checking the wrong URLs and correcting
Them. But it needs all my time and impossible as the website growing. 

 
 
 
-------Original Message-------
 
From: chuckroastpligg
Date: 02/01/15 00:21:55
To: Pligg/pligg-cms
Cc: tamouchin
Subject: Re: [pligg-cms] pligg adds extra characters to the submitted urls
(#206)
 
That is Unicode.. Try turning off url validation in admin > submit >
validate url > set to false. Then try submitting a new link and see if it
still happens.. Make sure you are submitting a NEW URL after changing that
setting. See if that makes a difference. 
—
Reply to this email directly or view it on GitHub.
 

---
Denne e-posten har blitt sjekket for virus av antivirusprogramvare fra Avast
http://www.avast.com

**Comment by chuckroastpligg** [comment] 2015-02-01 15:23
You should post in the support area on the Pligg website. More eyes on a problem gets solved quicker.

**Comment by tamouchin** [comment] 2015-02-01 15:26
Thanx a lot for good ideas 

 
 
 
-------Original Message-------
 
From: chuckroastpligg
Date: 2/1/2015 3:23:36 PM
To: Pligg/pligg-cms
Cc: tamouchin
Subject: Re: [pligg-cms] pligg adds extra characters to the submitted urls
(#206)
 
You should post in the support area on the Pligg website. More eyes on a
problem gets solved quicker.
—
Reply to this email directly or view it on GitHub.
 

---
Denne e-posten har blitt sjekket for virus av antivirusprogramvare fra Avast
http://www.avast.com

**Comment by chuckroastpligg** [comment] 2015-02-01 15:28
My guess is that this is a problem with the transliteration file and unicode.

**Comment by tamouchin** [comment] 2015-02-01 15:41
Could you please have a look in my admin or cplan to see if you can help me
to fix it? 
 
 
 
 
-------Original Message-------
 
From: chuckroastpligg
Date: 2/1/2015 3:28:29 PM
To: Pligg/pligg-cms
Cc: tamouchin
Subject: Re: [pligg-cms] pligg adds extra characters to the submitted urls
(#206)
 
My guess is that this is a problem with the transliteration file and unicode
 
—
Reply to this email directly or view it on GitHub.
 

---
Denne e-posten har blitt sjekket for virus av antivirusprogramvare fra Avast
http://www.avast.com

**Comment by chuckroastpligg** [comment] 2015-02-02 17:57
Closing this because it's not a Pligg bug. His problem is bad customization.

**Closed by chuckroastpligg** 2015-02-02 17:57 UTC

**Comment by tamouchin** [comment] 2015-09-12 21:09
Sorry to see when you do not know what the problem is just close the the topic saying bad customization.
