### ISSUE TITLE
Step 4 install 2.0.2

### ISSUE THREAD

**Issue by twixi** [Pligg/pligg-cms#228] opened 2015-09-14 11:05 UTC
Step 4
Creating database tables
Setting Pligg Version
Setting Captcha Method to SolveMedia
Adding default modules
Adding default widgets
Creating About Page
INSERT INTO `pligg_config` VALUES (1, 'SEO', '$URLMethod', '1', '1', '1 or 2', 'URL Method', 'blablabla', 'normal', NULL);Duplicate entry '1' for key 'PRIMARY'

**Comment by chuckroastpligg** [comment] 2015-09-14 15:48
This is not a bug, nor is it even an error. Closing the issue since it has absolutely no place here.

**Closed as completed by chuckroastpligg** 2015-09-14 15:48 UTC
